<?php
namespace FreePBX\modules\Frogman\Dialplan;

/**
 * Base class for dialplan templates.
 */
abstract class TemplateBase {

	/**
	 * Template identifier.
	 */
	abstract public function id();

	/**
	 * Human-readable name.
	 */
	abstract public function name();

	/**
	 * Description of what this template builds.
	 */
	abstract public function description();

	/**
	 * Example natural language that triggers this template.
	 */
	abstract public function examples();

	/**
	 * Generate the dialplan context block.
	 * Returns the full text to append to extensions_custom.conf.
	 */
	abstract public function generate($params);

	/**
	 * Validate the parameter map before generate() is allowed to run.
	 * Return true on success, or a string error message on failure.
	 * Implementations should:
	 *   1. Call $this->rejectDangerous($params) first as a framework-level guard.
	 *   2. Apply per-parameter whitelist checks for everything that gets
	 *      interpolated into dialplan text.
	 * See GHSA-pxfc-q72v-jh8m for the underlying CVE.
	 */
	abstract public function validateParams($params);

	/**
	 * Generate a context name from params.
	 */
	protected function contextName($prefix, $params) {
		$id = $params['extension'] ?? $params['name'] ?? $params['did'] ?? 'custom';
		$clean = preg_replace('/[^a-zA-Z0-9]/', '-', strtolower($id));
		return "oc-{$prefix}-{$clean}";
	}

	/**
	 * Build a priority-numbered extension block.
	 * Takes an array of app calls, returns numbered exten lines.
	 */
	protected function buildExten($exten, $apps) {
		$lines = [];
		foreach ($apps as $i => $app) {
			$pri = ($i === 0) ? '1' : 'n';
			$lines[] = "exten => {$exten},{$pri},{$app}";
		}
		return $lines;
	}

	/**
	 * Header comment for generated contexts.
	 */
	protected function header($description) {
		$timestamp = date('Y-m-d H:i:s');
		return "; Generated by Frogman on {$timestamp}\n; {$description}";
	}

	// ── Validation helpers (GHSA-pxfc-q72v-jh8m) ─────────────────

	/**
	 * Framework-level reject for the single most dangerous characters in any
	 * dialplan parameter: carriage return, newline, and null byte. Any of these
	 * in any value would let a caller break out of the intended Asterisk
	 * dialplan line and inject new directives — System(), Set(SHELL(...)),
	 * unexpected Goto, etc. Templates may have more permissive value rules
	 * (e.g. URLs with query strings), but newlines are never legitimate.
	 *
	 * Walks the param tree recursively.
	 */
	protected function rejectDangerous($params, $path = '') {
		if (!is_array($params)) {
			if (is_string($params) && preg_match('/[\r\n\0]/', $params)) {
				return "Parameter '{$path}' contains a control character (newline/CR/null) which is not allowed in dialplan templates";
			}
			return null;
		}
		foreach ($params as $key => $value) {
			$childPath = $path === '' ? (string)$key : "{$path}.{$key}";
			if (is_string($key) && preg_match('/[\r\n\0]/', $key)) {
				return "Parameter key '{$childPath}' contains a control character which is not allowed";
			}
			$err = $this->rejectDangerous($value, $childPath);
			if ($err !== null) return $err;
		}
		return null;
	}

	/**
	 * Digits only — extensions, ring group numbers, queue numbers.
	 */
	protected function isDigits($value) {
		return is_string($value) && preg_match('/^\d+$/', $value) === 1
			|| is_int($value);
	}

	/**
	 * Feature code: `*` followed by digits (e.g. *99).
	 */
	protected function isFeatureCode($value) {
		return is_string($value) && preg_match('/^\*\d+$/', $value) === 1;
	}

	/**
	 * Asterisk sound file reference — directory-style path of safe chars.
	 * Examples: `vm-goodbye`, `custom/frogman-greeting`, `digits/1`.
	 */
	protected function isSoundFile($value) {
		return is_string($value) && preg_match('#^[a-zA-Z0-9_./-]+$#', $value) === 1
			&& strpos($value, '..') === false;
	}

	/**
	 * HH:MM time format.
	 */
	protected function isTime($value) {
		if (!is_string($value)) return false;
		if (!preg_match('/^(\d{1,2}):(\d{2})$/', $value, $m)) return false;
		return (int)$m[1] <= 23 && (int)$m[2] <= 59;
	}

	/**
	 * Asterisk day-of-week spec. Accepts: `mon-fri`, `mon|wed|fri`, `*`, single day.
	 */
	protected function isDays($value) {
		return is_string($value) && preg_match('/^(\*|[a-z]{3}(-[a-z]{3})?(\|[a-z]{3}(-[a-z]{3})?)*)$/i', $value) === 1;
	}

	/**
	 * Destination spec — either a numeric extension/group/queue/etc., or
	 * a context,exten,priority triple referencing internal dialplan, or
	 * a "voicemail" / "vm" keyword (optionally followed by digits).
	 *
	 * Anything else needs to be rejected to keep callers from synthesizing
	 * raw dialplan text via the "dest" channel.
	 */
	protected function isDestination($value) {
		if ($this->isDigits($value)) return true;
		if (!is_string($value)) return false;
		// voicemail / vm keyword
		if (preg_match('/^(voicemail|vm)\d*$/i', $value)) return true;
		// hangup keyword
		if (strtolower($value) === 'hangup') return true;
		// context,exten,priority — Asterisk identifier shape
		if (preg_match('/^[a-zA-Z][a-zA-Z0-9_-]*,[a-zA-Z0-9_*#-]+,(\d+|n)$/', $value)) return true;
		return false;
	}

	/**
	 * HTTP/HTTPS URL. filter_var rejects newlines and most malformed URLs;
	 * we additionally disallow backticks and `$(` / `${` outside an explicit
	 * placeholder convention.
	 */
	protected function isUrl($value) {
		if (!is_string($value)) return false;
		if (!preg_match('#^https?://#i', $value)) return false;
		if (filter_var($value, FILTER_VALIDATE_URL) === false) return false;
		// Allow {callerid}/{phone}-style placeholders which templates substitute
		// pre-generation, but disallow `${...}` and backticks in raw input.
		if (preg_match('/[`]/', $value)) return false;
		if (preg_match('/\$\{[^}]+\}/', $value)) return false;
		return true;
	}

	/**
	 * Generic identifier — alphanumeric + underscore + dash. Used for action
	 * keywords, response_field names, prompt names, etc.
	 */
	protected function isIdentifier($value) {
		return is_string($value) && preg_match('/^[a-zA-Z0-9_-]+$/', $value) === 1;
	}

	/**
	 * Membership in a fixed allowlist of strings (case-insensitive).
	 */
	protected function inSet($value, array $allowed) {
		if (!is_string($value)) return false;
		$lower = strtolower($value);
		foreach ($allowed as $a) {
			if (strtolower($a) === $lower) return true;
		}
		return false;
	}
}
